// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MapObjectsStatus.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Map {

  /// <summary>Holder for reflection information generated from MapObjectsStatus.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class MapObjectsStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for MapObjectsStatus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapObjectsStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZNYXBPYmplY3RzU3RhdHVzLnByb3RvEg5QT0dPUHJvdG9zLk1hcCpFChBN",
            "YXBPYmplY3RzU3RhdHVzEhAKDFVOU0VUX1NUQVRVUxAAEgsKB1NVQ0NFU1MQ",
            "ARISCg5MT0NBVElPTl9VTlNFVBACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Map.MapObjectsStatus), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MapObjectsStatus {
    [pbr::OriginalName("UNSET_STATUS")] UnsetStatus = 0,
    [pbr::OriginalName("SUCCESS")] Success = 1,
    [pbr::OriginalName("LOCATION_UNSET")] LocationUnset = 2,
  }

  #endregion

}

#endregion Designer generated code
