// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecycleInventoryItemResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from RecycleInventoryItemResponse.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class RecycleInventoryItemResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for RecycleInventoryItemResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RecycleInventoryItemResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJSZWN5Y2xlSW52ZW50b3J5SXRlbVJlc3BvbnNlLnByb3RvEh9QT0dPUHJv",
            "dG9zLk5ldHdvcmtpbmcuUmVzcG9uc2VzIusBChxSZWN5Y2xlSW52ZW50b3J5",
            "SXRlbVJlc3BvbnNlElQKBnJlc3VsdBgBIAEoDjJELlBPR09Qcm90b3MuTmV0",
            "d29ya2luZy5SZXNwb25zZXMuUmVjeWNsZUludmVudG9yeUl0ZW1SZXNwb25z",
            "ZS5SZXN1bHQSEQoJbmV3X2NvdW50GAIgASgFImIKBlJlc3VsdBIJCgVVTlNF",
            "VBAAEgsKB1NVQ0NFU1MQARIbChdFUlJPUl9OT1RfRU5PVUdIX0NPUElFUxAC",
            "EiMKH0VSUk9SX0NBTk5PVF9SRUNZQ0xFX0lOQ1VCQVRPUlMQA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.RecycleInventoryItemResponse), global::POGOProtos.Networking.Responses.RecycleInventoryItemResponse.Parser, new[]{ "Result", "NewCount" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.RecycleInventoryItemResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class RecycleInventoryItemResponse : pb::IMessage<RecycleInventoryItemResponse> {
    private static readonly pb::MessageParser<RecycleInventoryItemResponse> _parser = new pb::MessageParser<RecycleInventoryItemResponse>(() => new RecycleInventoryItemResponse());
    public static pb::MessageParser<RecycleInventoryItemResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.RecycleInventoryItemResponseReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public RecycleInventoryItemResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public RecycleInventoryItemResponse(RecycleInventoryItemResponse other) : this() {
      result_ = other.result_;
      newCount_ = other.newCount_;
    }

    public RecycleInventoryItemResponse Clone() {
      return new RecycleInventoryItemResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.RecycleInventoryItemResponse.Types.Result result_ = 0;
    public global::POGOProtos.Networking.Responses.RecycleInventoryItemResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "new_count" field.</summary>
    public const int NewCountFieldNumber = 2;
    private int newCount_;
    public int NewCount {
      get { return newCount_; }
      set {
        newCount_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as RecycleInventoryItemResponse);
    }

    public bool Equals(RecycleInventoryItemResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (NewCount != other.NewCount) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (NewCount != 0) hash ^= NewCount.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (NewCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NewCount);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (NewCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NewCount);
      }
      return size;
    }

    public void MergeFrom(RecycleInventoryItemResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.NewCount != 0) {
        NewCount = other.NewCount;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.RecycleInventoryItemResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 16: {
            NewCount = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the RecycleInventoryItemResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_NOT_ENOUGH_COPIES")] ErrorNotEnoughCopies = 2,
        [pbr::OriginalName("ERROR_CANNOT_RECYCLE_INCUBATORS")] ErrorCannotRecycleIncubators = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
