// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SetFavoritePokemonResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from SetFavoritePokemonResponse.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class SetFavoritePokemonResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for SetFavoritePokemonResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SetFavoritePokemonResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBTZXRGYXZvcml0ZVBva2Vtb25SZXNwb25zZS5wcm90bxIfUE9HT1Byb3Rv",
            "cy5OZXR3b3JraW5nLlJlc3BvbnNlcyLJAQoaU2V0RmF2b3JpdGVQb2tlbW9u",
            "UmVzcG9uc2USUgoGcmVzdWx0GAEgASgOMkIuUE9HT1Byb3Rvcy5OZXR3b3Jr",
            "aW5nLlJlc3BvbnNlcy5TZXRGYXZvcml0ZVBva2Vtb25SZXNwb25zZS5SZXN1",
            "bHQiVwoGUmVzdWx0EgkKBVVOU0VUEAASCwoHU1VDQ0VTUxABEhsKF0VSUk9S",
            "X1BPS0VNT05fTk9UX0ZPVU5EEAISGAoURVJST1JfUE9LRU1PTl9JU19FR0cQ",
            "A2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.SetFavoritePokemonResponse), global::POGOProtos.Networking.Responses.SetFavoritePokemonResponse.Parser, new[]{ "Result" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.SetFavoritePokemonResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SetFavoritePokemonResponse : pb::IMessage<SetFavoritePokemonResponse> {
    private static readonly pb::MessageParser<SetFavoritePokemonResponse> _parser = new pb::MessageParser<SetFavoritePokemonResponse>(() => new SetFavoritePokemonResponse());
    public static pb::MessageParser<SetFavoritePokemonResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.SetFavoritePokemonResponseReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public SetFavoritePokemonResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public SetFavoritePokemonResponse(SetFavoritePokemonResponse other) : this() {
      result_ = other.result_;
    }

    public SetFavoritePokemonResponse Clone() {
      return new SetFavoritePokemonResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.SetFavoritePokemonResponse.Types.Result result_ = 0;
    public global::POGOProtos.Networking.Responses.SetFavoritePokemonResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as SetFavoritePokemonResponse);
    }

    public bool Equals(SetFavoritePokemonResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      return size;
    }

    public void MergeFrom(SetFavoritePokemonResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.SetFavoritePokemonResponse.Types.Result) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the SetFavoritePokemonResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_POKEMON_NOT_FOUND")] ErrorPokemonNotFound = 2,
        [pbr::OriginalName("ERROR_POKEMON_IS_EGG")] ErrorPokemonIsEgg = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
