// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActivityType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from ActivityType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ActivityTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ActivityType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActivityTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJBY3Rpdml0eVR5cGUucHJvdG8SEFBPR09Qcm90b3MuRW51bXMq7AUKDEFj",
            "dGl2aXR5VHlwZRIUChBBQ1RJVklUWV9VTktOT1dOEAASGgoWQUNUSVZJVFlf",
            "Q0FUQ0hfUE9LRU1PThABEiEKHUFDVElWSVRZX0NBVENIX0xFR0VORF9QT0tF",
            "TU9OEAISGQoVQUNUSVZJVFlfRkxFRV9QT0tFTU9OEAMSGAoUQUNUSVZJVFlf",
            "REVGRUFUX0ZPUlQQBBIbChdBQ1RJVklUWV9FVk9MVkVfUE9LRU1PThAFEhYK",
            "EkFDVElWSVRZX0hBVENIX0VHRxAGEhQKEEFDVElWSVRZX1dBTEtfS00QBxIe",
            "ChpBQ1RJVklUWV9QT0tFREVYX0VOVFJZX05FVxAIEh4KGkFDVElWSVRZX0NB",
            "VENIX0ZJUlNUX1RIUk9XEAkSHQoZQUNUSVZJVFlfQ0FUQ0hfTklDRV9USFJP",
            "VxAKEh4KGkFDVElWSVRZX0NBVENIX0dSRUFUX1RIUk9XEAsSIgoeQUNUSVZJ",
            "VFlfQ0FUQ0hfRVhDRUxMRU5UX1RIUk9XEAwSHAoYQUNUSVZJVFlfQ0FUQ0hf",
            "Q1VSVkVCQUxMEA0SJQohQUNUSVZJVFlfQ0FUQ0hfRklSU1RfQ0FUQ0hfT0Zf",
            "REFZEA4SHAoYQUNUSVZJVFlfQ0FUQ0hfTUlMRVNUT05FEA8SGgoWQUNUSVZJ",
            "VFlfVFJBSU5fUE9LRU1PThAQEhgKFEFDVElWSVRZX1NFQVJDSF9GT1JUEBES",
            "HAoYQUNUSVZJVFlfUkVMRUFTRV9QT0tFTU9OEBISIgoeQUNUSVZJVFlfSEFU",
            "Q0hfRUdHX1NNQUxMX0JPTlVTEBMSIwofQUNUSVZJVFlfSEFUQ0hfRUdHX01F",
            "RElVTV9CT05VUxAUEiIKHkFDVElWSVRZX0hBVENIX0VHR19MQVJHRV9CT05V",
            "UxAVEiAKHEFDVElWSVRZX0RFRkVBVF9HWU1fREVGRU5ERVIQFhIeChpBQ1RJ",
            "VklUWV9ERUZFQVRfR1lNX0xFQURFUhAXYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.ActivityType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ActivityType {
    [pbr::OriginalName("ACTIVITY_UNKNOWN")] ActivityUnknown = 0,
    [pbr::OriginalName("ACTIVITY_CATCH_POKEMON")] ActivityCatchPokemon = 1,
    [pbr::OriginalName("ACTIVITY_CATCH_LEGEND_POKEMON")] ActivityCatchLegendPokemon = 2,
    [pbr::OriginalName("ACTIVITY_FLEE_POKEMON")] ActivityFleePokemon = 3,
    [pbr::OriginalName("ACTIVITY_DEFEAT_FORT")] ActivityDefeatFort = 4,
    [pbr::OriginalName("ACTIVITY_EVOLVE_POKEMON")] ActivityEvolvePokemon = 5,
    [pbr::OriginalName("ACTIVITY_HATCH_EGG")] ActivityHatchEgg = 6,
    [pbr::OriginalName("ACTIVITY_WALK_KM")] ActivityWalkKm = 7,
    [pbr::OriginalName("ACTIVITY_POKEDEX_ENTRY_NEW")] ActivityPokedexEntryNew = 8,
    [pbr::OriginalName("ACTIVITY_CATCH_FIRST_THROW")] ActivityCatchFirstThrow = 9,
    [pbr::OriginalName("ACTIVITY_CATCH_NICE_THROW")] ActivityCatchNiceThrow = 10,
    [pbr::OriginalName("ACTIVITY_CATCH_GREAT_THROW")] ActivityCatchGreatThrow = 11,
    [pbr::OriginalName("ACTIVITY_CATCH_EXCELLENT_THROW")] ActivityCatchExcellentThrow = 12,
    [pbr::OriginalName("ACTIVITY_CATCH_CURVEBALL")] ActivityCatchCurveball = 13,
    [pbr::OriginalName("ACTIVITY_CATCH_FIRST_CATCH_OF_DAY")] ActivityCatchFirstCatchOfDay = 14,
    [pbr::OriginalName("ACTIVITY_CATCH_MILESTONE")] ActivityCatchMilestone = 15,
    [pbr::OriginalName("ACTIVITY_TRAIN_POKEMON")] ActivityTrainPokemon = 16,
    [pbr::OriginalName("ACTIVITY_SEARCH_FORT")] ActivitySearchFort = 17,
    [pbr::OriginalName("ACTIVITY_RELEASE_POKEMON")] ActivityReleasePokemon = 18,
    [pbr::OriginalName("ACTIVITY_HATCH_EGG_SMALL_BONUS")] ActivityHatchEggSmallBonus = 19,
    [pbr::OriginalName("ACTIVITY_HATCH_EGG_MEDIUM_BONUS")] ActivityHatchEggMediumBonus = 20,
    [pbr::OriginalName("ACTIVITY_HATCH_EGG_LARGE_BONUS")] ActivityHatchEggLargeBonus = 21,
    [pbr::OriginalName("ACTIVITY_DEFEAT_GYM_DEFENDER")] ActivityDefeatGymDefender = 22,
    [pbr::OriginalName("ACTIVITY_DEFEAT_GYM_LEADER")] ActivityDefeatGymLeader = 23,
  }

  #endregion

}

#endregion Designer generated code
