// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BadgeType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from BadgeType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class BadgeTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for BadgeType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BadgeTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9CYWRnZVR5cGUucHJvdG8SEFBPR09Qcm90b3MuRW51bXMqoQcKCUJhZGdl",
            "VHlwZRIPCgtCQURHRV9VTlNFVBAAEhMKD0JBREdFX1RSQVZFTF9LTRABEhkK",
            "FUJBREdFX1BPS0VERVhfRU5UUklFUxACEhcKE0JBREdFX0NBUFRVUkVfVE9U",
            "QUwQAxIXChNCQURHRV9ERUZFQVRFRF9GT1JUEAQSFwoTQkFER0VfRVZPTFZF",
            "RF9UT1RBTBAFEhcKE0JBREdFX0hBVENIRURfVE9UQUwQBhIbChdCQURHRV9F",
            "TkNPVU5URVJFRF9UT1RBTBAHEhsKF0JBREdFX1BPS0VTVE9QU19WSVNJVEVE",
            "EAgSGgoWQkFER0VfVU5JUVVFX1BPS0VTVE9QUxAJEhkKFUJBREdFX1BPS0VC",
            "QUxMX1RIUk9XThAKEhYKEkJBREdFX0JJR19NQUdJS0FSUBALEhgKFEJBREdF",
            "X0RFUExPWUVEX1RPVEFMEAwSGwoXQkFER0VfQkFUVExFX0FUVEFDS19XT04Q",
            "DRIdChlCQURHRV9CQVRUTEVfVFJBSU5JTkdfV09OEA4SGwoXQkFER0VfQkFU",
            "VExFX0RFRkVORF9XT04QDxIZChVCQURHRV9QUkVTVElHRV9SQUlTRUQQEBIa",
            "ChZCQURHRV9QUkVTVElHRV9EUk9QUEVEEBESFQoRQkFER0VfVFlQRV9OT1JN",
            "QUwQEhIXChNCQURHRV9UWVBFX0ZJR0hUSU5HEBMSFQoRQkFER0VfVFlQRV9G",
            "TFlJTkcQFBIVChFCQURHRV9UWVBFX1BPSVNPThAVEhUKEUJBREdFX1RZUEVf",
            "R1JPVU5EEBYSEwoPQkFER0VfVFlQRV9ST0NLEBcSEgoOQkFER0VfVFlQRV9C",
            "VUcQGBIUChBCQURHRV9UWVBFX0dIT1NUEBkSFAoQQkFER0VfVFlQRV9TVEVF",
            "TBAaEhMKD0JBREdFX1RZUEVfRklSRRAbEhQKEEJBREdFX1RZUEVfV0FURVIQ",
            "HBIUChBCQURHRV9UWVBFX0dSQVNTEB0SFwoTQkFER0VfVFlQRV9FTEVDVFJJ",
            "QxAeEhYKEkJBREdFX1RZUEVfUFNZQ0hJQxAfEhIKDkJBREdFX1RZUEVfSUNF",
            "ECASFQoRQkFER0VfVFlQRV9EUkFHT04QIRITCg9CQURHRV9UWVBFX0RBUksQ",
            "IhIUChBCQURHRV9UWVBFX0ZBSVJZECMSFwoTQkFER0VfU01BTExfUkFUVEFU",
            "QRAkEhEKDUJBREdFX1BJS0FDSFUQJWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.BadgeType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum BadgeType {
    [pbr::OriginalName("BADGE_UNSET")] BadgeUnset = 0,
    [pbr::OriginalName("BADGE_TRAVEL_KM")] BadgeTravelKm = 1,
    [pbr::OriginalName("BADGE_POKEDEX_ENTRIES")] BadgePokedexEntries = 2,
    [pbr::OriginalName("BADGE_CAPTURE_TOTAL")] BadgeCaptureTotal = 3,
    [pbr::OriginalName("BADGE_DEFEATED_FORT")] BadgeDefeatedFort = 4,
    [pbr::OriginalName("BADGE_EVOLVED_TOTAL")] BadgeEvolvedTotal = 5,
    [pbr::OriginalName("BADGE_HATCHED_TOTAL")] BadgeHatchedTotal = 6,
    [pbr::OriginalName("BADGE_ENCOUNTERED_TOTAL")] BadgeEncounteredTotal = 7,
    [pbr::OriginalName("BADGE_POKESTOPS_VISITED")] BadgePokestopsVisited = 8,
    [pbr::OriginalName("BADGE_UNIQUE_POKESTOPS")] BadgeUniquePokestops = 9,
    [pbr::OriginalName("BADGE_POKEBALL_THROWN")] BadgePokeballThrown = 10,
    [pbr::OriginalName("BADGE_BIG_MAGIKARP")] BadgeBigMagikarp = 11,
    [pbr::OriginalName("BADGE_DEPLOYED_TOTAL")] BadgeDeployedTotal = 12,
    [pbr::OriginalName("BADGE_BATTLE_ATTACK_WON")] BadgeBattleAttackWon = 13,
    [pbr::OriginalName("BADGE_BATTLE_TRAINING_WON")] BadgeBattleTrainingWon = 14,
    [pbr::OriginalName("BADGE_BATTLE_DEFEND_WON")] BadgeBattleDefendWon = 15,
    [pbr::OriginalName("BADGE_PRESTIGE_RAISED")] BadgePrestigeRaised = 16,
    [pbr::OriginalName("BADGE_PRESTIGE_DROPPED")] BadgePrestigeDropped = 17,
    [pbr::OriginalName("BADGE_TYPE_NORMAL")] Normal = 18,
    [pbr::OriginalName("BADGE_TYPE_FIGHTING")] Fighting = 19,
    [pbr::OriginalName("BADGE_TYPE_FLYING")] Flying = 20,
    [pbr::OriginalName("BADGE_TYPE_POISON")] Poison = 21,
    [pbr::OriginalName("BADGE_TYPE_GROUND")] Ground = 22,
    [pbr::OriginalName("BADGE_TYPE_ROCK")] Rock = 23,
    [pbr::OriginalName("BADGE_TYPE_BUG")] Bug = 24,
    [pbr::OriginalName("BADGE_TYPE_GHOST")] Ghost = 25,
    [pbr::OriginalName("BADGE_TYPE_STEEL")] Steel = 26,
    [pbr::OriginalName("BADGE_TYPE_FIRE")] Fire = 27,
    [pbr::OriginalName("BADGE_TYPE_WATER")] Water = 28,
    [pbr::OriginalName("BADGE_TYPE_GRASS")] Grass = 29,
    [pbr::OriginalName("BADGE_TYPE_ELECTRIC")] Electric = 30,
    [pbr::OriginalName("BADGE_TYPE_PSYCHIC")] Psychic = 31,
    [pbr::OriginalName("BADGE_TYPE_ICE")] Ice = 32,
    [pbr::OriginalName("BADGE_TYPE_DRAGON")] Dragon = 33,
    [pbr::OriginalName("BADGE_TYPE_DARK")] Dark = 34,
    [pbr::OriginalName("BADGE_TYPE_FAIRY")] Fairy = 35,
    [pbr::OriginalName("BADGE_SMALL_RATTATA")] BadgeSmallRattata = 36,
    [pbr::OriginalName("BADGE_PIKACHU")] BadgePikachu = 37,
  }

  #endregion

}

#endregion Designer generated code
