// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraInterpolation.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from CameraInterpolation.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CameraInterpolationReflection {

    #region Descriptor
    /// <summary>File descriptor for CameraInterpolation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CameraInterpolationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDYW1lcmFJbnRlcnBvbGF0aW9uLnByb3RvEhBQT0dPUHJvdG9zLkVudW1z",
            "KpYBChNDYW1lcmFJbnRlcnBvbGF0aW9uEhIKDkNBTV9JTlRFUlBfQ1VUEAAS",
            "FQoRQ0FNX0lOVEVSUF9MSU5FQVIQARIVChFDQU1fSU5URVJQX1NNT09USBAC",
            "EiUKIUNBTV9JTlRFUlBfU01PT1RIX1JPVF9MSU5FQVJfTU9WRRADEhYKEkNB",
            "TV9JTlRFUlBfREVQRU5EUxAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.CameraInterpolation), }, null));
    }
    #endregion

  }
  #region Enums
  public enum CameraInterpolation {
    [pbr::OriginalName("CAM_INTERP_CUT")] CamInterpCut = 0,
    [pbr::OriginalName("CAM_INTERP_LINEAR")] CamInterpLinear = 1,
    [pbr::OriginalName("CAM_INTERP_SMOOTH")] CamInterpSmooth = 2,
    [pbr::OriginalName("CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE")] CamInterpSmoothRotLinearMove = 3,
    [pbr::OriginalName("CAM_INTERP_DEPENDS")] CamInterpDepends = 4,
  }

  #endregion

}

#endregion Designer generated code
