// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemCategory.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from ItemCategory.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ItemCategoryReflection {

    #region Descriptor
    /// <summary>File descriptor for ItemCategory.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemCategoryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJJdGVtQ2F0ZWdvcnkucHJvdG8SEFBPR09Qcm90b3MuRW51bXMq1gIKDEl0",
            "ZW1DYXRlZ29yeRIWChJJVEVNX0NBVEVHT1JZX05PTkUQABIaChZJVEVNX0NB",
            "VEVHT1JZX1BPS0VCQUxMEAESFgoSSVRFTV9DQVRFR09SWV9GT09EEAISGgoW",
            "SVRFTV9DQVRFR09SWV9NRURJQ0lORRADEhcKE0lURU1fQ0FURUdPUllfQk9P",
            "U1QQBBIaChZJVEVNX0NBVEVHT1JZX1VUSUxJVEVTEAUSGAoUSVRFTV9DQVRF",
            "R09SWV9DQU1FUkEQBhIWChJJVEVNX0NBVEVHT1JZX0RJU0sQBxIbChdJVEVN",
            "X0NBVEVHT1JZX0lOQ1VCQVRPUhAIEhkKFUlURU1fQ0FURUdPUllfSU5DRU5T",
            "RRAJEhoKFklURU1fQ0FURUdPUllfWFBfQk9PU1QQChIjCh9JVEVNX0NBVEVH",
            "T1JZX0lOVkVOVE9SWV9VUEdSQURFEAtiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.ItemCategory), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ItemCategory {
    [pbr::OriginalName("ITEM_CATEGORY_NONE")] None = 0,
    [pbr::OriginalName("ITEM_CATEGORY_POKEBALL")] Pokeball = 1,
    [pbr::OriginalName("ITEM_CATEGORY_FOOD")] Food = 2,
    [pbr::OriginalName("ITEM_CATEGORY_MEDICINE")] Medicine = 3,
    [pbr::OriginalName("ITEM_CATEGORY_BOOST")] Boost = 4,
    [pbr::OriginalName("ITEM_CATEGORY_UTILITES")] Utilites = 5,
    [pbr::OriginalName("ITEM_CATEGORY_CAMERA")] Camera = 6,
    [pbr::OriginalName("ITEM_CATEGORY_DISK")] Disk = 7,
    [pbr::OriginalName("ITEM_CATEGORY_INCUBATOR")] Incubator = 8,
    [pbr::OriginalName("ITEM_CATEGORY_INCENSE")] Incense = 9,
    [pbr::OriginalName("ITEM_CATEGORY_XP_BOOST")] XpBoost = 10,
    [pbr::OriginalName("ITEM_CATEGORY_INVENTORY_UPGRADE")] InventoryUpgrade = 11,
  }

  #endregion

}

#endregion Designer generated code
