// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Platform.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from Platform.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class PlatformReflection {

    #region Descriptor
    /// <summary>File descriptor for Platform.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlatformReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5QbGF0Zm9ybS5wcm90bxIQUE9HT1Byb3Rvcy5FbnVtcypBCghQbGF0Zm9y",
            "bRIJCgVVTlNFVBAAEgcKA0lPUxABEgsKB0FORFJPSUQQAhIHCgNPU1gQAxIL",
            "CgdXSU5ET1dTEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.Platform), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Platform {
    [pbr::OriginalName("UNSET")] Unset = 0,
    [pbr::OriginalName("IOS")] Ios = 1,
    [pbr::OriginalName("ANDROID")] Android = 2,
    [pbr::OriginalName("OSX")] Osx = 3,
    [pbr::OriginalName("WINDOWS")] Windows = 4,
  }

  #endregion

}

#endregion Designer generated code
