// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PokemonType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from PokemonType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class PokemonTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for PokemonType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PokemonTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQb2tlbW9uVHlwZS5wcm90bxIQUE9HT1Byb3Rvcy5FbnVtcyraAwoLUG9r",
            "ZW1vblR5cGUSFQoRUE9LRU1PTl9UWVBFX05PTkUQABIXChNQT0tFTU9OX1RZ",
            "UEVfTk9STUFMEAESGQoVUE9LRU1PTl9UWVBFX0ZJR0hUSU5HEAISFwoTUE9L",
            "RU1PTl9UWVBFX0ZMWUlORxADEhcKE1BPS0VNT05fVFlQRV9QT0lTT04QBBIX",
            "ChNQT0tFTU9OX1RZUEVfR1JPVU5EEAUSFQoRUE9LRU1PTl9UWVBFX1JPQ0sQ",
            "BhIUChBQT0tFTU9OX1RZUEVfQlVHEAcSFgoSUE9LRU1PTl9UWVBFX0dIT1NU",
            "EAgSFgoSUE9LRU1PTl9UWVBFX1NURUVMEAkSFQoRUE9LRU1PTl9UWVBFX0ZJ",
            "UkUQChIWChJQT0tFTU9OX1RZUEVfV0FURVIQCxIWChJQT0tFTU9OX1RZUEVf",
            "R1JBU1MQDBIZChVQT0tFTU9OX1RZUEVfRUxFQ1RSSUMQDRIYChRQT0tFTU9O",
            "X1RZUEVfUFNZQ0hJQxAOEhQKEFBPS0VNT05fVFlQRV9JQ0UQDxIXChNQT0tF",
            "TU9OX1RZUEVfRFJBR09OEBASFQoRUE9LRU1PTl9UWVBFX0RBUksQERIWChJQ",
            "T0tFTU9OX1RZUEVfRkFJUlkQEmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.PokemonType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PokemonType {
    [pbr::OriginalName("POKEMON_TYPE_NONE")] None = 0,
    [pbr::OriginalName("POKEMON_TYPE_NORMAL")] Normal = 1,
    [pbr::OriginalName("POKEMON_TYPE_FIGHTING")] Fighting = 2,
    [pbr::OriginalName("POKEMON_TYPE_FLYING")] Flying = 3,
    [pbr::OriginalName("POKEMON_TYPE_POISON")] Poison = 4,
    [pbr::OriginalName("POKEMON_TYPE_GROUND")] Ground = 5,
    [pbr::OriginalName("POKEMON_TYPE_ROCK")] Rock = 6,
    [pbr::OriginalName("POKEMON_TYPE_BUG")] Bug = 7,
    [pbr::OriginalName("POKEMON_TYPE_GHOST")] Ghost = 8,
    [pbr::OriginalName("POKEMON_TYPE_STEEL")] Steel = 9,
    [pbr::OriginalName("POKEMON_TYPE_FIRE")] Fire = 10,
    [pbr::OriginalName("POKEMON_TYPE_WATER")] Water = 11,
    [pbr::OriginalName("POKEMON_TYPE_GRASS")] Grass = 12,
    [pbr::OriginalName("POKEMON_TYPE_ELECTRIC")] Electric = 13,
    [pbr::OriginalName("POKEMON_TYPE_PSYCHIC")] Psychic = 14,
    [pbr::OriginalName("POKEMON_TYPE_ICE")] Ice = 15,
    [pbr::OriginalName("POKEMON_TYPE_DRAGON")] Dragon = 16,
    [pbr::OriginalName("POKEMON_TYPE_DARK")] Dark = 17,
    [pbr::OriginalName("POKEMON_TYPE_FAIRY")] Fairy = 18,
  }

  #endregion

}

#endregion Designer generated code
