// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PokemonFamilyId.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from PokemonFamilyId.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class PokemonFamilyIdReflection {

    #region Descriptor
    /// <summary>File descriptor for PokemonFamilyId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PokemonFamilyIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVQb2tlbW9uRmFtaWx5SWQucHJvdG8SEFBPR09Qcm90b3MuRW51bXMq+gwK",
            "D1Bva2Vtb25GYW1pbHlJZBIQCgxGQU1JTFlfVU5TRVQQABIUChBGQU1JTFlf",
            "QlVMQkFTQVVSEAESFQoRRkFNSUxZX0NIQVJNQU5ERVIQBBITCg9GQU1JTFlf",
            "U1FVSVJUTEUQBxITCg9GQU1JTFlfQ0FURVJQSUUQChIRCg1GQU1JTFlfV0VF",
            "RExFEA0SEQoNRkFNSUxZX1BJREdFWRAQEhIKDkZBTUlMWV9SQVRUQVRBEBMS",
            "EgoORkFNSUxZX1NQRUFST1cQFRIQCgxGQU1JTFlfRUtBTlMQFxISCg5GQU1J",
            "TFlfUElLQUNIVRAZEhQKEEZBTUlMWV9TQU5EU0hSRVcQGxIZChVGQU1JTFlf",
            "TklET1JBTl9GRU1BTEUQHRIXChNGQU1JTFlfTklET1JBTl9NQUxFECASEwoP",
            "RkFNSUxZX0NMRUZBSVJZECMSEQoNRkFNSUxZX1ZVTFBJWBAlEhUKEUZBTUlM",
            "WV9KSUdHTFlQVUZGECcSEAoMRkFNSUxZX1pVQkFUECkSEQoNRkFNSUxZX09E",
            "RElTSBArEhAKDEZBTUlMWV9QQVJBUxAuEhIKDkZBTUlMWV9WRU5PTkFUEDAS",
            "EgoORkFNSUxZX0RJR0xFVFQQMhIRCg1GQU1JTFlfTUVPV1RIEDQSEgoORkFN",
            "SUxZX1BTWURVQ0sQNhIRCg1GQU1JTFlfTUFOS0VZEDgSFAoQRkFNSUxZX0dS",
            "T1dMSVRIRRA6EhIKDkZBTUlMWV9QT0xJV0FHEDwSDwoLRkFNSUxZX0FCUkEQ",
            "PxIRCg1GQU1JTFlfTUFDSE9QEEISFQoRRkFNSUxZX0JFTExTUFJPVVQQRRIU",
            "ChBGQU1JTFlfVEVOVEFDT09MEEgSEgoORkFNSUxZX0dFT0RVREUQShIRCg1G",
            "QU1JTFlfUE9OWVRBEE0SEwoPRkFNSUxZX1NMT1dQT0tFEE8SFAoQRkFNSUxZ",
            "X01BR05FTUlURRBREhQKEEZBTUlMWV9GQVJGRVRDSEQQUxIQCgxGQU1JTFlf",
            "RE9EVU8QVBIPCgtGQU1JTFlfU0VFTBBWEhEKDUZBTUlMWV9HUklNRVIQWBIT",
            "Cg9GQU1JTFlfU0hFTExERVIQWhIRCg1GQU1JTFlfR0FTVExZEFwSDwoLRkFN",
            "SUxZX09OSVgQXxISCg5GQU1JTFlfRFJPV1pFRRBgEhAKDEZBTUlMWV9IWVBO",
            "TxBhEhEKDUZBTUlMWV9LUkFCQlkQYhISCg5GQU1JTFlfVk9MVE9SQhBkEhQK",
            "EEZBTUlMWV9FWEVHR0NVVEUQZhIRCg1GQU1JTFlfQ1VCT05FEGgSFAoQRkFN",
            "SUxZX0hJVE1PTkxFRRBqEhUKEUZBTUlMWV9ISVRNT05DSEFOEGsSFAoQRkFN",
            "SUxZX0xJQ0tJVFVORxBsEhIKDkZBTUlMWV9LT0ZGSU5HEG0SEgoORkFNSUxZ",
            "X1JIWUhPUk4QbxISCg5GQU1JTFlfQ0hBTlNFWRBxEhIKDkZBTUlMWV9UQU5H",
            "RUxBEHISFQoRRkFNSUxZX0tBTkdBU0tIQU4QcxIRCg1GQU1JTFlfSE9SU0VB",
            "EHQSEgoORkFNSUxZX0dPTERFRU4QdhIRCg1GQU1JTFlfU1RBUllVEHgSEgoO",
            "RkFNSUxZX01SX01JTUUQehISCg5GQU1JTFlfU0NZVEhFUhB7Eg8KC0ZBTUlM",
            "WV9KWU5YEHwSFQoRRkFNSUxZX0VMRUNUQUJVWloQfRIRCg1GQU1JTFlfTUFH",
            "TUFSEH4SEQoNRkFNSUxZX1BJTlNJUhB/EhIKDUZBTUlMWV9UQVVST1MQgAES",
            "FAoPRkFNSUxZX01BR0lLQVJQEIEBEhIKDUZBTUlMWV9MQVBSQVMQgwESEQoM",
            "RkFNSUxZX0RJVFRPEIQBEhEKDEZBTUlMWV9FRVZFRRCFARITCg5GQU1JTFlf",
            "UE9SWUdPThCJARITCg5GQU1JTFlfT01BTllURRCKARISCg1GQU1JTFlfS0FC",
            "VVRPEIwBEhYKEUZBTUlMWV9BRVJPREFDVFlMEI4BEhMKDkZBTUlMWV9TTk9S",
            "TEFYEI8BEhQKD0ZBTUlMWV9BUlRJQ1VOTxCQARISCg1GQU1JTFlfWkFQRE9T",
            "EJEBEhMKDkZBTUlMWV9NT0xUUkVTEJIBEhMKDkZBTUlMWV9EUkFUSU5JEJMB",
            "EhIKDUZBTUlMWV9NRVdUV08QlgESDwoKRkFNSUxZX01FVxCXAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.PokemonFamilyId), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PokemonFamilyId {
    [pbr::OriginalName("FAMILY_UNSET")] FamilyUnset = 0,
    [pbr::OriginalName("FAMILY_BULBASAUR")] FamilyBulbasaur = 1,
    [pbr::OriginalName("FAMILY_CHARMANDER")] FamilyCharmander = 4,
    [pbr::OriginalName("FAMILY_SQUIRTLE")] FamilySquirtle = 7,
    [pbr::OriginalName("FAMILY_CATERPIE")] FamilyCaterpie = 10,
    [pbr::OriginalName("FAMILY_WEEDLE")] FamilyWeedle = 13,
    [pbr::OriginalName("FAMILY_PIDGEY")] FamilyPidgey = 16,
    [pbr::OriginalName("FAMILY_RATTATA")] FamilyRattata = 19,
    [pbr::OriginalName("FAMILY_SPEAROW")] FamilySpearow = 21,
    [pbr::OriginalName("FAMILY_EKANS")] FamilyEkans = 23,
    [pbr::OriginalName("FAMILY_PIKACHU")] FamilyPikachu = 25,
    [pbr::OriginalName("FAMILY_SANDSHREW")] FamilySandshrew = 27,
    [pbr::OriginalName("FAMILY_NIDORAN_FEMALE")] FamilyNidoranFemale = 29,
    [pbr::OriginalName("FAMILY_NIDORAN_MALE")] FamilyNidoranMale = 32,
    [pbr::OriginalName("FAMILY_CLEFAIRY")] FamilyClefairy = 35,
    [pbr::OriginalName("FAMILY_VULPIX")] FamilyVulpix = 37,
    [pbr::OriginalName("FAMILY_JIGGLYPUFF")] FamilyJigglypuff = 39,
    [pbr::OriginalName("FAMILY_ZUBAT")] FamilyZubat = 41,
    [pbr::OriginalName("FAMILY_ODDISH")] FamilyOddish = 43,
    [pbr::OriginalName("FAMILY_PARAS")] FamilyParas = 46,
    [pbr::OriginalName("FAMILY_VENONAT")] FamilyVenonat = 48,
    [pbr::OriginalName("FAMILY_DIGLETT")] FamilyDiglett = 50,
    [pbr::OriginalName("FAMILY_MEOWTH")] FamilyMeowth = 52,
    [pbr::OriginalName("FAMILY_PSYDUCK")] FamilyPsyduck = 54,
    [pbr::OriginalName("FAMILY_MANKEY")] FamilyMankey = 56,
    [pbr::OriginalName("FAMILY_GROWLITHE")] FamilyGrowlithe = 58,
    [pbr::OriginalName("FAMILY_POLIWAG")] FamilyPoliwag = 60,
    [pbr::OriginalName("FAMILY_ABRA")] FamilyAbra = 63,
    [pbr::OriginalName("FAMILY_MACHOP")] FamilyMachop = 66,
    [pbr::OriginalName("FAMILY_BELLSPROUT")] FamilyBellsprout = 69,
    [pbr::OriginalName("FAMILY_TENTACOOL")] FamilyTentacool = 72,
    [pbr::OriginalName("FAMILY_GEODUDE")] FamilyGeodude = 74,
    [pbr::OriginalName("FAMILY_PONYTA")] FamilyPonyta = 77,
    [pbr::OriginalName("FAMILY_SLOWPOKE")] FamilySlowpoke = 79,
    [pbr::OriginalName("FAMILY_MAGNEMITE")] FamilyMagnemite = 81,
    [pbr::OriginalName("FAMILY_FARFETCHD")] FamilyFarfetchd = 83,
    [pbr::OriginalName("FAMILY_DODUO")] FamilyDoduo = 84,
    [pbr::OriginalName("FAMILY_SEEL")] FamilySeel = 86,
    [pbr::OriginalName("FAMILY_GRIMER")] FamilyGrimer = 88,
    [pbr::OriginalName("FAMILY_SHELLDER")] FamilyShellder = 90,
    [pbr::OriginalName("FAMILY_GASTLY")] FamilyGastly = 92,
    [pbr::OriginalName("FAMILY_ONIX")] FamilyOnix = 95,
    [pbr::OriginalName("FAMILY_DROWZEE")] FamilyDrowzee = 96,
    [pbr::OriginalName("FAMILY_HYPNO")] FamilyHypno = 97,
    [pbr::OriginalName("FAMILY_KRABBY")] FamilyKrabby = 98,
    [pbr::OriginalName("FAMILY_VOLTORB")] FamilyVoltorb = 100,
    [pbr::OriginalName("FAMILY_EXEGGCUTE")] FamilyExeggcute = 102,
    [pbr::OriginalName("FAMILY_CUBONE")] FamilyCubone = 104,
    [pbr::OriginalName("FAMILY_HITMONLEE")] FamilyHitmonlee = 106,
    [pbr::OriginalName("FAMILY_HITMONCHAN")] FamilyHitmonchan = 107,
    [pbr::OriginalName("FAMILY_LICKITUNG")] FamilyLickitung = 108,
    [pbr::OriginalName("FAMILY_KOFFING")] FamilyKoffing = 109,
    [pbr::OriginalName("FAMILY_RHYHORN")] FamilyRhyhorn = 111,
    [pbr::OriginalName("FAMILY_CHANSEY")] FamilyChansey = 113,
    [pbr::OriginalName("FAMILY_TANGELA")] FamilyTangela = 114,
    [pbr::OriginalName("FAMILY_KANGASKHAN")] FamilyKangaskhan = 115,
    [pbr::OriginalName("FAMILY_HORSEA")] FamilyHorsea = 116,
    [pbr::OriginalName("FAMILY_GOLDEEN")] FamilyGoldeen = 118,
    [pbr::OriginalName("FAMILY_STARYU")] FamilyStaryu = 120,
    [pbr::OriginalName("FAMILY_MR_MIME")] FamilyMrMime = 122,
    [pbr::OriginalName("FAMILY_SCYTHER")] FamilyScyther = 123,
    [pbr::OriginalName("FAMILY_JYNX")] FamilyJynx = 124,
    [pbr::OriginalName("FAMILY_ELECTABUZZ")] FamilyElectabuzz = 125,
    [pbr::OriginalName("FAMILY_MAGMAR")] FamilyMagmar = 126,
    [pbr::OriginalName("FAMILY_PINSIR")] FamilyPinsir = 127,
    [pbr::OriginalName("FAMILY_TAUROS")] FamilyTauros = 128,
    [pbr::OriginalName("FAMILY_MAGIKARP")] FamilyMagikarp = 129,
    [pbr::OriginalName("FAMILY_LAPRAS")] FamilyLapras = 131,
    [pbr::OriginalName("FAMILY_DITTO")] FamilyDitto = 132,
    [pbr::OriginalName("FAMILY_EEVEE")] FamilyEevee = 133,
    [pbr::OriginalName("FAMILY_PORYGON")] FamilyPorygon = 137,
    [pbr::OriginalName("FAMILY_OMANYTE")] FamilyOmanyte = 138,
    [pbr::OriginalName("FAMILY_KABUTO")] FamilyKabuto = 140,
    [pbr::OriginalName("FAMILY_AERODACTYL")] FamilyAerodactyl = 142,
    [pbr::OriginalName("FAMILY_SNORLAX")] FamilySnorlax = 143,
    [pbr::OriginalName("FAMILY_ARTICUNO")] FamilyArticuno = 144,
    [pbr::OriginalName("FAMILY_ZAPDOS")] FamilyZapdos = 145,
    [pbr::OriginalName("FAMILY_MOLTRES")] FamilyMoltres = 146,
    [pbr::OriginalName("FAMILY_DRATINI")] FamilyDratini = 147,
    [pbr::OriginalName("FAMILY_MEWTWO")] FamilyMewtwo = 150,
    [pbr::OriginalName("FAMILY_MEW")] FamilyMew = 151,
  }

  #endregion

}

#endregion Designer generated code
