// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TutorialState.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from TutorialState.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class TutorialStateReflection {

    #region Descriptor
    /// <summary>File descriptor for TutorialState.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TutorialStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNUdXRvcmlhbFN0YXRlLnByb3RvEhBQT0dPUHJvdG9zLkVudW1zKuQBCg1U",
            "dXRvcmlhbFN0YXRlEhAKDExFR0FMX1NDUkVFThAAEhQKEEFWQVRBUl9TRUxF",
            "Q1RJT04QARIUChBBQ0NPVU5UX0NSRUFUSU9OEAISEwoPUE9LRU1PTl9DQVBU",
            "VVJFEAMSEgoOTkFNRV9TRUxFQ1RJT04QBBIRCg1QT0tFTU9OX0JFUlJZEAUS",
            "DAoIVVNFX0lURU0QBhIiCh5GSVJTVF9USU1FX0VYUEVSSUVOQ0VfQ09NUExF",
            "VEUQBxIVChFQT0tFU1RPUF9UVVRPUklBTBAIEhAKDEdZTV9UVVRPUklBTBAJ",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.TutorialState), }, null));
    }
    #endregion

  }
  #region Enums
  public enum TutorialState {
    [pbr::OriginalName("LEGAL_SCREEN")] LegalScreen = 0,
    [pbr::OriginalName("AVATAR_SELECTION")] AvatarSelection = 1,
    [pbr::OriginalName("ACCOUNT_CREATION")] AccountCreation = 2,
    [pbr::OriginalName("POKEMON_CAPTURE")] PokemonCapture = 3,
    [pbr::OriginalName("NAME_SELECTION")] NameSelection = 4,
    [pbr::OriginalName("POKEMON_BERRY")] PokemonBerry = 5,
    [pbr::OriginalName("USE_ITEM")] UseItem = 6,
    [pbr::OriginalName("FIRST_TIME_EXPERIENCE_COMPLETE")] FirstTimeExperienceComplete = 7,
    [pbr::OriginalName("POKESTOP_TUTORIAL")] PokestopTutorial = 8,
    [pbr::OriginalName("GYM_TUTORIAL")] GymTutorial = 9,
  }

  #endregion

}

#endregion Designer generated code
