// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FortType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Map.Fort {

  /// <summary>Holder for reflection information generated from FortType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class FortTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for FortType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FortTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Gb3J0VHlwZS5wcm90bxITUE9HT1Byb3Rvcy5NYXAuRm9ydCojCghGb3J0",
            "VHlwZRIHCgNHWU0QABIOCgpDSEVDS1BPSU5UEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Map.Fort.FortType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum FortType {
    [pbr::OriginalName("GYM")] Gym = 0,
    [pbr::OriginalName("CHECKPOINT")] Checkpoint = 1,
  }

  #endregion

}

#endregion Designer generated code
