// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectDailyBonusMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Requests.Messages {

  /// <summary>Holder for reflection information generated from CollectDailyBonusMessage.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CollectDailyBonusMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for CollectDailyBonusMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CollectDailyBonusMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Db2xsZWN0RGFpbHlCb251c01lc3NhZ2UucHJvdG8SJ1BPR09Qcm90b3Mu",
            "TmV0d29ya2luZy5SZXF1ZXN0cy5NZXNzYWdlcyIaChhDb2xsZWN0RGFpbHlC",
            "b251c01lc3NhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Requests.Messages.CollectDailyBonusMessage), global::POGOProtos.Networking.Requests.Messages.CollectDailyBonusMessage.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  No message needed.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CollectDailyBonusMessage : pb::IMessage<CollectDailyBonusMessage> {
    private static readonly pb::MessageParser<CollectDailyBonusMessage> _parser = new pb::MessageParser<CollectDailyBonusMessage>(() => new CollectDailyBonusMessage());
    public static pb::MessageParser<CollectDailyBonusMessage> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Requests.Messages.CollectDailyBonusMessageReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public CollectDailyBonusMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    public CollectDailyBonusMessage(CollectDailyBonusMessage other) : this() {
    }

    public CollectDailyBonusMessage Clone() {
      return new CollectDailyBonusMessage(this);
    }

    public override bool Equals(object other) {
      return Equals(other as CollectDailyBonusMessage);
    }

    public bool Equals(CollectDailyBonusMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
    }

    public int CalculateSize() {
      int size = 0;
      return size;
    }

    public void MergeFrom(CollectDailyBonusMessage other) {
      if (other == null) {
        return;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
