// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectDailyDefenderBonusMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Requests.Messages {

  /// <summary>Holder for reflection information generated from CollectDailyDefenderBonusMessage.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CollectDailyDefenderBonusMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for CollectDailyDefenderBonusMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CollectDailyDefenderBonusMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZDb2xsZWN0RGFpbHlEZWZlbmRlckJvbnVzTWVzc2FnZS5wcm90bxInUE9H",
            "T1Byb3Rvcy5OZXR3b3JraW5nLlJlcXVlc3RzLk1lc3NhZ2VzIiIKIENvbGxl",
            "Y3REYWlseURlZmVuZGVyQm9udXNNZXNzYWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage), global::POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  No message needed.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CollectDailyDefenderBonusMessage : pb::IMessage<CollectDailyDefenderBonusMessage> {
    private static readonly pb::MessageParser<CollectDailyDefenderBonusMessage> _parser = new pb::MessageParser<CollectDailyDefenderBonusMessage>(() => new CollectDailyDefenderBonusMessage());
    public static pb::MessageParser<CollectDailyDefenderBonusMessage> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessageReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public CollectDailyDefenderBonusMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    public CollectDailyDefenderBonusMessage(CollectDailyDefenderBonusMessage other) : this() {
    }

    public CollectDailyDefenderBonusMessage Clone() {
      return new CollectDailyDefenderBonusMessage(this);
    }

    public override bool Equals(object other) {
      return Equals(other as CollectDailyDefenderBonusMessage);
    }

    public bool Equals(CollectDailyDefenderBonusMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
    }

    public int CalculateSize() {
      int size = 0;
      return size;
    }

    public void MergeFrom(CollectDailyDefenderBonusMessage other) {
      if (other == null) {
        return;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
