// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EggIncubatorType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Inventory {

  /// <summary>Holder for reflection information generated from EggIncubatorType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class EggIncubatorTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for EggIncubatorType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EggIncubatorTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZFZ2dJbmN1YmF0b3JUeXBlLnByb3RvEhRQT0dPUHJvdG9zLkludmVudG9y",
            "eSo/ChBFZ2dJbmN1YmF0b3JUeXBlEhMKD0lOQ1VCQVRPUl9VTlNFVBAAEhYK",
            "EklOQ1VCQVRPUl9ESVNUQU5DRRABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Inventory.EggIncubatorType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EggIncubatorType {
    [pbr::OriginalName("INCUBATOR_UNSET")] IncubatorUnset = 0,
    [pbr::OriginalName("INCUBATOR_DISTANCE")] IncubatorDistance = 1,
  }

  #endregion

}

#endregion Designer generated code
