// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemId.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Inventory {

  /// <summary>Holder for reflection information generated from ItemId.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ItemIdReflection {

    #region Descriptor
    /// <summary>File descriptor for ItemId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxJdGVtSWQucHJvdG8SFFBPR09Qcm90b3MuSW52ZW50b3J5KscFCgZJdGVt",
            "SWQSEAoMSVRFTV9VTktOT1dOEAASEgoOSVRFTV9QT0tFX0JBTEwQARITCg9J",
            "VEVNX0dSRUFUX0JBTEwQAhITCg9JVEVNX1VMVFJBX0JBTEwQAxIUChBJVEVN",
            "X01BU1RFUl9CQUxMEAQSDwoLSVRFTV9QT1RJT04QZRIVChFJVEVNX1NVUEVS",
            "X1BPVElPThBmEhUKEUlURU1fSFlQRVJfUE9USU9OEGcSEwoPSVRFTV9NQVhf",
            "UE9USU9OEGgSEAoLSVRFTV9SRVZJVkUQyQESFAoPSVRFTV9NQVhfUkVWSVZF",
            "EMoBEhMKDklURU1fTFVDS1lfRUdHEK0CEhoKFUlURU1fSU5DRU5TRV9PUkRJ",
            "TkFSWRCRAxIXChJJVEVNX0lOQ0VOU0VfU1BJQ1kQkgMSFgoRSVRFTV9JTkNF",
            "TlNFX0NPT0wQkwMSGAoTSVRFTV9JTkNFTlNFX0ZMT1JBTBCUAxITCg5JVEVN",
            "X1RST1lfRElTSxD1AxISCg1JVEVNX1hfQVRUQUNLENoEEhMKDklURU1fWF9E",
            "RUZFTlNFENsEEhMKDklURU1fWF9NSVJBQ0xFENwEEhQKD0lURU1fUkFaWl9C",
            "RVJSWRC9BRIUCg9JVEVNX0JMVUtfQkVSUlkQvgUSFQoQSVRFTV9OQU5BQl9C",
            "RVJSWRC/BRIVChBJVEVNX1dFUEFSX0JFUlJZEMAFEhUKEElURU1fUElOQVBf",
            "QkVSUlkQwQUSGAoTSVRFTV9TUEVDSUFMX0NBTUVSQRChBhIjCh5JVEVNX0lO",
            "Q1VCQVRPUl9CQVNJQ19VTkxJTUlURUQQhQcSGQoUSVRFTV9JTkNVQkFUT1Jf",
            "QkFTSUMQhgcSIQocSVRFTV9QT0tFTU9OX1NUT1JBR0VfVVBHUkFERRDpBxIe",
            "ChlJVEVNX0lURU1fU1RPUkFHRV9VUEdSQURFEOoHYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Inventory.ItemId), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ItemId {
    [pbr::OriginalName("ITEM_UNKNOWN")] ItemUnknown = 0,
    [pbr::OriginalName("ITEM_POKE_BALL")] ItemPokeBall = 1,
    [pbr::OriginalName("ITEM_GREAT_BALL")] ItemGreatBall = 2,
    [pbr::OriginalName("ITEM_ULTRA_BALL")] ItemUltraBall = 3,
    [pbr::OriginalName("ITEM_MASTER_BALL")] ItemMasterBall = 4,
    [pbr::OriginalName("ITEM_POTION")] ItemPotion = 101,
    [pbr::OriginalName("ITEM_SUPER_POTION")] ItemSuperPotion = 102,
    [pbr::OriginalName("ITEM_HYPER_POTION")] ItemHyperPotion = 103,
    [pbr::OriginalName("ITEM_MAX_POTION")] ItemMaxPotion = 104,
    [pbr::OriginalName("ITEM_REVIVE")] ItemRevive = 201,
    [pbr::OriginalName("ITEM_MAX_REVIVE")] ItemMaxRevive = 202,
    [pbr::OriginalName("ITEM_LUCKY_EGG")] ItemLuckyEgg = 301,
    [pbr::OriginalName("ITEM_INCENSE_ORDINARY")] ItemIncenseOrdinary = 401,
    [pbr::OriginalName("ITEM_INCENSE_SPICY")] ItemIncenseSpicy = 402,
    [pbr::OriginalName("ITEM_INCENSE_COOL")] ItemIncenseCool = 403,
    [pbr::OriginalName("ITEM_INCENSE_FLORAL")] ItemIncenseFloral = 404,
    [pbr::OriginalName("ITEM_TROY_DISK")] ItemTroyDisk = 501,
    [pbr::OriginalName("ITEM_X_ATTACK")] ItemXAttack = 602,
    [pbr::OriginalName("ITEM_X_DEFENSE")] ItemXDefense = 603,
    [pbr::OriginalName("ITEM_X_MIRACLE")] ItemXMiracle = 604,
    [pbr::OriginalName("ITEM_RAZZ_BERRY")] ItemRazzBerry = 701,
    [pbr::OriginalName("ITEM_BLUK_BERRY")] ItemBlukBerry = 702,
    [pbr::OriginalName("ITEM_NANAB_BERRY")] ItemNanabBerry = 703,
    [pbr::OriginalName("ITEM_WEPAR_BERRY")] ItemWeparBerry = 704,
    [pbr::OriginalName("ITEM_PINAP_BERRY")] ItemPinapBerry = 705,
    [pbr::OriginalName("ITEM_SPECIAL_CAMERA")] ItemSpecialCamera = 801,
    [pbr::OriginalName("ITEM_INCUBATOR_BASIC_UNLIMITED")] ItemIncubatorBasicUnlimited = 901,
    [pbr::OriginalName("ITEM_INCUBATOR_BASIC")] ItemIncubatorBasic = 902,
    [pbr::OriginalName("ITEM_POKEMON_STORAGE_UPGRADE")] ItemPokemonStorageUpgrade = 1001,
    [pbr::OriginalName("ITEM_ITEM_STORAGE_UPGRADE")] ItemItemStorageUpgrade = 1002,
  }

  #endregion

}

#endregion Designer generated code
